In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
comb = pd.read_csv('./title_abstract_combined_with_names.csv')

In [3]:
comb

      absID                             combine_title_abstract
0         1  New geographical records of parasitic nematode...
1         2  Detection of Batrachochytrium dendrobatidis in...
2         3  Experimental life history of Spirometra erinac...
3         7  Parasite infectivity to hybridising host speci...
4         8  Environmental constraints influencing survival...
...     ...                                                ...
1280  61080  The delicate pygmy rice rat (Oligoryzomys deli...
1281  61081  Outbreak of hantavirus pulmonary syndrome, Los...
1282  61085  Infectious disease survey of gemsbok in New Me...
1283  61100  VENEZUELAN EQUINE ENCEPHALITIS VIRUS FROM SOUT...
1284  61102  Sequence analysis of the complete S genomic se...

[1285 rows x 2 columns]

In [5]:
meta_file = '../hp-extractor/raw_data/hp_metadata.tsv'
abstracts_file = '../hp-extractor/raw_data/hp_abstracts.tsv'
names_file = '../hp-extractor/raw_data/abs_with_verbatim_names.csv'

meta = pd.read_csv(meta_file, sep='\t')
abstracts = pd.read_csv(abstracts_file, sep='\t')
names = pd.read_csv(names_file)

/var/folders/fw/dxz3_sjn07q2pt5qw1dpn0ww0000gn/T/ipykernel_37350/797120470.py:5: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  meta = pd.read_csv(meta_file, sep='\t')

In [30]:
names

,absID,parasite,host,combine_abstract
0,1,rhabdias sphaerocephala,bufo bufo,New geographical records of parasitic nematode...
1,2,batrachochytrium dendrobatidis,eurycea neotenes,Detection of Batrachochytrium dendrobatidis in...
2,3,spirometra erinaceieuropaei,rana nigromaculata,Experimental life history of Spirometra erinac...
3,7,protopolystoma xenopodis,xenopus laevis,Parasite infectivity to hybridising host speci...
4,8,protopolystoma xenopodis,xenopus laevis,Environmental constraints influencing survival...
...,...,...,...,...
1280,61080,andes,oligoryzomys fulvescens,The delicate pygmy rice rat (Oligoryzomys deli...
1281,61081,sin nombre,oligoryzomys fulvescens,"Outbreak of hantavirus pulmonary syndrome, Los..."
1282,61085,bluetongue,oryx gazella,Infectious disease survey of gemsbok in New Me...
1283,61100,venezuelan equine encephalitis,peromyscus gossypinus,VENEZUELAN EQUINE ENCEPHALITIS VIRUS FROM SOUT...
1284,61102,sin nombre,peromyscus maniculatus,Sequence analysis of the complete S genomic se...

In [33]:
names_min = names[['absID', 'combine_abstract']]

In [34]:
names_min

      absID                                   combine_abstract
0         1  New geographical records of parasitic nematode...
1         2  Detection of Batrachochytrium dendrobatidis in...
2         3  Experimental life history of Spirometra erinac...
3         7  Parasite infectivity to hybridising host speci...
4         8  Environmental constraints influencing survival...
...     ...                                                ...
1280  61080  The delicate pygmy rice rat (Oligoryzomys deli...
1281  61081  Outbreak of hantavirus pulmonary syndrome, Los...
1282  61085  Infectious disease survey of gemsbok in New Me...
1283  61100  VENEZUELAN EQUINE ENCEPHALITIS VIRUS FROM SOUT...
1284  61102  Sequence analysis of the complete S genomic se...

[1285 rows x 2 columns]

In [35]:
names_min.to_csv('title_abstract_combined_with_names.csv', index=None)

In [7]:
for index, row in abstracts.iterrows():
    
    absID = row['absID']

    title = meta[meta['absID'] == absID]['title'].values[0]
    abs = row['abs']
    
    if type(title) == float:
        title = ''

    combined_abstract = str(title) + ' ' + str(abs)

    abstracts.loc[index, 'title_abstract'] = combined_abstract

In [9]:
abstracts_min = abstracts[['absID', 'title_abstract']]

In [10]:
abstracts_min

       absID                                     title_abstract
0          1  New geographical records of parasitic nematode...
1          2  Detection of Batrachochytrium dendrobatidis in...
2          3  Experimental life history of Spirometra erinac...
3          4  Origin of the amphibian chytrid fungus. The su...
4          5  Effects of temperature on oviposition rate in ...
...      ...                                                ...
61162  61163  Isolation and molecular characterization of a ...
61163  61164  Fatal cetacean morbillivirus infection in an A...
61164  61165   Polar bear (Ursus maritimus) morbillivirus in...
61165  61166  Bovine viral diarrhea virus in alpaca: abortio...
61166  61167  Consensus nested PCR amplification and sequenc...

[61167 rows x 2 columns]

In [11]:
abstracts_min.to_csv('title_abstract_all.csv', index=None)

In [12]:
virus_abs = pd.read_csv('../hp_extractor/hp-extractor/raw_data/virus_abstracts.csv')

In [16]:
abstracts_min_virus = abstracts_min[abstracts_min['absID'].isin(virus_abs['absID'])]

In [17]:
abstracts_min_virus

       absID                                     title_abstract
52        53  Avian host and mosquito (Diptera: Culicidae) v...
53        54  Host feeding pattern of Culex quinquefasciatus...
54        55  Blood-feeding patterns of the Culex pipiens co...
55        56  Pathogenicity of a quail (Coturnix coturnix ja...
56        57  Transactivation of latent Marek's disease herp...
...      ...                                                ...
61162  61163  Isolation and molecular characterization of a ...
61163  61164  Fatal cetacean morbillivirus infection in an A...
61164  61165   Polar bear (Ursus maritimus) morbillivirus in...
61165  61166  Bovine viral diarrhea virus in alpaca: abortio...
61166  61167  Consensus nested PCR amplification and sequenc...

[17551 rows x 2 columns]

In [18]:
abstracts_min_virus.to_csv('title_abstract_virus.csv', index=None)

In [13]:
virus_abs

       absID
0         53
1         54
2         55
3         56
4         57
...      ...
17546  61163
17547  61164
17548  61165
17549  61166
17550  61167

[17551 rows x 1 columns]

In [ ]:
for index, row in names.iterrows():
    
    absID = row['absID']
    title = meta[meta['absID'] == absID]['title'].values[0]
    abs = abstracts[abstracts['absID'] == absID]['abs'].values[0]
    host = meta[meta['absID'] == absID]['Host'].values[0]
    host_original = meta[meta['absID'] == absID]['Host_original'].values[0]
    parasite = meta[meta['absID'] == absID]['Parasite'].values[0]
    parasite_original = meta[meta['absID'] == absID]['Parasite_original'].values[0]
    
    if type(title) == float:
        title = ''

    combined_abstract = str(title) + ' ' + str(abs)

    names.loc[index, 'parasite'] = parasite
    names.loc[index, 'host'] = host
    names.loc[index, 'combine_abstract'] = combined_abstract

In [4]:
meta

,Database,Host,Host_original,Parasite,Parasite_original,ParasiteType,ReferenceText,pmid,title,journal,absID
0,EID2,bufo bufo,NaN,rhabdias sphaerocephala,rhabdias sphaerocephala,helminth,"Galli P, 2001, Parassitologia, 43",12402520.0,New geographical records of parasitic nematode...,Parassitologia,1
1,EID2,eurycea neotenes,NaN,batrachochytrium dendrobatidis,batrachochytrium dendrobatidis,fungi,"Gaertner JP, 2009, Ecohealth, 6",19424755.0,Detection of Batrachochytrium dendrobatidis in...,EcoHealth,2
2,EID2,rana nigromaculata,NaN,spirometra erinaceieuropaei,spirometra erinaceieuropaei,helminth,"Lee SH, 1990, Kisaengchunghak Chapchi, 28",2095198.0,Experimental life history of Spirometra erinacei.,Kisaengch'unghak chapchi. The Korean journal o...,3
3,EID2,canis lupus familiaris,NaN,spirometra erinaceieuropaei,spirometra erinaceieuropaei,helminth,"Lee SH, 1990, Kisaengchunghak Chapchi, 28",2095198.0,Experimental life history of Spirometra erinacei.,Kisaengch'unghak chapchi. The Korean journal o...,3
4,EID2,felis catus,NaN,spirometra erinaceieuropaei,spirometra erinaceieuropaei,helminth,"Lee SH, 1990, Kisaengchunghak Chapchi, 28",2095198.0,Experimental life history of Spirometra erinacei.,Kisaengch'unghak chapchi. The Korean journal o...,3
...,...,...,...,...,...,...,...,...,...,...,...
185357,HP3,zygodontomys brevicauda,NaN,cano delgadito,cano delgadito,virus,Fulhorst et al. 1999,10463688.0,Natural rodent host associations of Guanarito ...,The American journal of tropical medicine and ...,58922
185358,HP3,zygodontomys brevicauda,NaN,guanarito,guanarito,virus,Fulhorst et al. 2001,11508391.0,Experimental infection of Neotoma albigula (Mu...,The American journal of tropical medicine and ...,61067
185359,HP3,zygodontomys brevicauda,NaN,guanarito,guanarito,virus,Fulhorst et al. 2001,11384516.0,Geographic distribution and genetic diversity ...,Emerging infectious diseases,58956
185360,HP3,zygodontomys brevicauda,NaN,pirital,pirital,virus,Fulhorst et al. 1999,10463688.0,Natural rodent host associations of Guanarito ...,The American journal of tropical medicine and ...,58922
185361,HP3,zygodontomys brevicauda,NaN,sin nombre,sin nombre,virus,Bayard et al. 2004,15498167.0,"Outbreak of hantavirus pulmonary syndrome, Los...",Emerging infectious diseases,61081

In [5]:
abstracts

                                                     abs  absID
0      To provide information on parasites of Bufo bu...      1
1      A nested PCR protocol was used to analyze five...      2
2      The complete life cycle of Spirometra erinacei...      3
3      The sudden appearance of chytridiomycosis, the...      4
4      Protopolystoma xenopodis is an oviparous monog...      5
...                                                  ...    ...
61162  A cytopathic infectious agent was isolated fro...  61163
61163  A juvenile offshore bottlenose dolphin (Tursio...  61164
61164  Polar bear (Ursus maritimus) morbillivirus inf...  61165
61165  An alpaca herd in eastern Ontario experienced ...  61166
61166  The orthoreoviruses are segmented RNA viruses ...  61167

[61167 rows x 2 columns]